module "vpc" {
  source = "../../terraform-aws-vpc"
  project_name = var.project
  environment = var.envi
  common_tags = var.common_tags
  vpc_tags = var.vpc_tags
  igw_tag = var.igw_tag
  public_subnet_tags = var.public_subnet_tags
  private_subnet_tags = var.private_subnet_tags
  database_subnet_tags = var.database_subnet_tags
  public_subnet_cidrs = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  database_subnet_cidrs = var.database_subnet_cidrs
  nat_gateway_tags = var.nat_gateway_tags
  public_route_table_tags = var.public_route_table_tags
  private_route_table_tags = var.private_route_table_tags
  database_route_table_tags = var.database_route_table_tags
  is_peering_required = var.is_peering_required
  peering_tags = var.peering_tags
}